/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jonathan.mybooklist.backoffice;


import com.jonathan.mybooklist.RepositoryFactory;
import com.jonathan.mybooklist.jpa.models.JpaModelFactory;
import com.jonathan.mybooklist.models.ModelFactory;
import  com.jonathan.mybooklist.jpa.repositoris.JpaRepositoryFactory;
import com.uvic.teknos.book.models.JdbcModelFactory;
import com.uvic.teknos.book.repositorys.JdbcRepositoryFactory;


import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws SQLException {
        RepositoryFactory repositoryFactory = new JdbcRepositoryFactory();
        ModelFactory modelFactory = new JdbcModelFactory();
        var backOffice = new BackOffice(System.in, System.out, repositoryFactory, modelFactory);
        backOffice.start();
    }
}
