import org.gradle.internal.impldep.org.junit.experimental.categories.Categories.CategoryFilter.include

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}


dependencies {
    implementation("de.vandermeer:asciitable:0.3.2")
    implementation(project(":domain"))
    implementation(project(":criptoutils"))
    implementation(project(":domain-implementation:jdbc"))
    implementation(project(":domain-implementation:jpa"))
    implementation("com.athaydes.rawhttp:rawhttp-core:2.6.0")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.google.code.gson:gson:2.9.1")


}

application {
    // Define the main class for the application.
    mainClass = "com.jonathan.mybooklist.services.App"
}
