/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jonathan.mybooklist.backoffice;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {

}
